name: Build Lightspeed RAG Containers

on:
  pull_request:
    paths:
      - 'containers/lightspeed-rag/**'
  push:
    tags:
      - 'v*'

env:
  REGISTRY: quay.io
  IMAGE_NAME: krkn-chaos/krknctl-lightspeed

jobs:
  build-arm64-nvidia:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Extract version from tag
        id: version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            echo "is_tag=true" >> $GITHUB_OUTPUT
          else
            echo "version=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
            echo "is_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: ./containers/lightspeed-rag
          file: ./containers/lightspeed-rag/Containerfile.nvidia
          platforms: linux/arm64
          push: ${{ steps.version.outputs.is_tag }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rag-model-nvidia-arm64.${{ steps.version.outputs.version }}
          build-args: |
            CODE_VERSION=${{ steps.version.outputs.version }}

  build-arm64-apple-silicon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Extract version from tag
        id: version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            echo "is_tag=true" >> $GITHUB_OUTPUT
          else
            echo "version=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
            echo "is_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: ./containers/lightspeed-rag
          file: ./containers/lightspeed-rag/Containerfile.apple-silicon
          platforms: linux/arm64
          push: ${{ steps.version.outputs.is_tag }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rag-model-apple-silicon-arm64.${{ steps.version.outputs.version }}
          build-args: |
            CODE_VERSION=${{ steps.version.outputs.version }}

  build-amd64-nvidia:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Extract version from tag
        id: version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            echo "is_tag=true" >> $GITHUB_OUTPUT
          else
            echo "version=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
            echo "is_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: ./containers/lightspeed-rag
          file: ./containers/lightspeed-rag/Containerfile.nvidia
          platforms: linux/amd64
          push: ${{ steps.version.outputs.is_tag }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rag-model-nvidia-amd64.${{ steps.version.outputs.version }}
          build-args: |
            CODE_VERSION=${{ steps.version.outputs.version }}

  build-amd64-generic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Extract version from tag
        id: version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            echo "is_tag=true" >> $GITHUB_OUTPUT
          else
            echo "version=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
            echo "is_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: ./containers/lightspeed-rag
          file: ./containers/lightspeed-rag/Containerfile.generic
          platforms: linux/amd64
          push: ${{ steps.version.outputs.is_tag }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rag-model-generic-amd64.${{ steps.version.outputs.version }}
          build-args: |
            CODE_VERSION=${{ steps.version.outputs.version }}

  create-manifests:
    runs-on: ubuntu-latest
    needs: [build-arm64-nvidia, build-arm64-apple-silicon, build-amd64-nvidia, build-amd64-generic]
    if: github.ref_type == 'tag'
    steps:
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Create and push multi-arch manifests
        run: |
          VERSION="${{ steps.version.outputs.version }}"

          # Create nvidia manifest (amd64 + arm64)
          docker manifest create \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rag-model-nvidia \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rag-model-nvidia-amd64.${VERSION} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rag-model-nvidia-arm64.${VERSION}

          docker manifest push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rag-model-nvidia

          # Create apple-silicon manifest (arm64 only)
          docker manifest create \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rag-model-apple-silicon \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rag-model-apple-silicon-arm64.${VERSION}

          docker manifest push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rag-model-apple-silicon

          # Create generic manifest (amd64 only for now)
          docker manifest create \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rag-model-generic \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rag-model-generic-amd64.${VERSION}

          docker manifest push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rag-model-generic