name: Build
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  format:
    name: Formatting tests
    strategy:
      matrix:
        #python-version: [ '3.9', '3.10', 'pypy3.9' ]
        python-version: [ '3.9' ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check isort, black, and flake8
        run: |
          pip install black flake8 isort
          isort --profile black $(git ls-files '*/*.py' '*.py')
          black --line-length 79 $(git ls-files '*/*.py' '*.py')
          flake8 $(git ls-files '*/*.py' '*.py')