name: Run Main Script

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Install expect for interactive automation
      run: |
        sudo apt-get update
        sudo apt-get install -y expect
    
    - name: Run main.py with automated interaction
      run: |
        expect << "EOD"
        set timeout 60
        spawn python main.py
        expect "Ask a question"
        send "what is krkn pod-scenarios?\r"
        expect "Ask a question"
        send "exit\r"
        EOD
        exit $?
      timeout-minutes: 5